language: c
dist: trusty
compiler:
    - gcc

before_install:
    - sudo apt-add-repository -y ppa:beineri/opt-qt591-trusty
    - sudo apt-get -qy update

install:
    - sudo apt-get -qy install doxygen graphviz qt59-meta-full cmake

before_script:
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_PREFIX_PATH=/opt/qt59/ -DCMAKE_BUILD_TYPE=Debug ..

script: make CC="$CC"

after_success: 
    - mkdir -p render_output
    - ./radiance_cli -b nyancat.gif -o render_output

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    target_branch: gh-pages
    local_dir: render_output
    on:
        branch: modelview


