language: c
compiler:
    - gcc
    - clang

before_install:
    - sudo add-apt-repository -y ppa:kalakris/cmake
    - sudo add-apt-repository -y ppa:team-xbmc/ppa
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq libsdl2-dev libgl1-mesa-dev libportmidi-dev libfftw3-dev libsamplerate0-dev
    - git clone --quiet --depth=100 "https://github.com/EddieRingle/portaudio" ~/builds/portaudio
      && pushd ~/builds/portaudio
      && ./configure
      && make CC="$CC"
      && sudo make install
      && popd;

script: make


