language: c
compiler:
    - gcc
    - clang

env:
    - CONFIGURE_FLAGS=
    - CONFIGURE_FLAGS=--without-vamp

install:
    - sudo apt-get install -qq libsdl2-dev libgl1-mesa-dev libportmidi-dev libfftw3-dev libsamplerate0-dev vamp-plugin-sdk
    - git clone --quiet --depth=100 "https://github.com/EddieRingle/portaudio" ~/builds/portaudio
      && pushd ~/builds/portaudio
      && ./configure
      && make
      && sudo make install
      && popd;

script: ./configure $CONFIGURE_FLAGS && make


