language: c
dist: trusty
compiler:
    - gcc

before_install:
    - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-add-repository -y ppa:beineri/opt-qt591-trusty
    - sudo add-apt-repository -y ppa:mc3man/testing6
    - sudo apt-get -qy update

install:
    - sudo apt-get install -qq g++-6
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
    - sudo apt-get -qy install doxygen graphviz qt59base qt59multimedia qt59quickcontrols qt59imageformats qt59quickcontrols2 qt59script libfftw3-dev libsamplerate0-dev libasound2-dev libmpv-dev
    - git clone --quiet --depth=100 "https://github.com/EddieRingle/portaudio" ~/builds/portaudio
      && pushd ~/builds/portaudio
      && ./configure
      && make
      && sudo make install
      && popd;
    - git clone --quiet --depth=100 "https://github.com/thestk/rtmidi" ~/builds/rtmidi
      && pushd ~/builds/rtmidi
      && ./autogen.sh
      && ./configure
      && make
      && sudo make install
      && popd;
    - curl https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage > /usr/local/bin/linuxdeployqt
    - sudo ldconfig

before_script:
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_PREFIX_PATH=/opt/qt59/ -DCMAKE_BUILD_TYPE=Release ..

script: make

after_success: 
    - mkdir -p render_output
    - ./radiance_cli -b nyancat.gif -o render_output
    - make bundle

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    target_branch: gh-pages-travis
    local_dir: render_output
    on:
        branch: modelview


